# GitLab CI/CD pipeline for Playwright TODOs app
# Stages: test -> report -> security -> troubleshoot

stages:
- test
- report
- security
- troubleshoot

variables:
  NODE_VERSION: "20"
  REPORTS_DIR: "playwright-report"
  SECURITY_REPORT: "security-report.json"
  NODE_OPTIONS: "--openssl-legacy-provider"
  APP_URL: "http://localhost:8080"

default:
  image: node:$NODE_VERSION
  before_script:
  - npm ci

# Stage 1: Run Playwright tests (includes starting the app)
run_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.55.1-focal
  script:
  - echo "Installing http-server..."
  - npm install -g http-server
  - echo "Starting TODO app..."
  - nohup http-server . -p 8080 -c-1 --silent > server.log 2>&1 &
  - sleep 5
  - echo "Server log:"
  - cat server.log
  - echo "Testing connectivity..."
  - curl -f $APP_URL || echo "App not responding"
  - echo "Waiting for app to be ready at $APP_URL..."
  - npx wait-on $APP_URL --timeout 300000 --interval 2000 --verbose
  - echo "Running Playwright tests..."
  - npx playwright test --reporter=html,junit --output $REPORTS_DIR
  artifacts:
    paths:
    - $REPORTS_DIR
    - server.log
    expire_in: 1 hour
  allow_failure: false

# Stage 2: Publish HTML report
html_report:
  stage: report
  script:
  - echo "Publishing HTML reports..."
  - mkdir -p public
  - cp -r $REPORTS_DIR/* public/
  artifacts:
    paths:
    - public
    reports:
      junit: $REPORTS_DIR/*.xml
    expire_in: 1 hour
  needs:
  - run_tests

# Stage 3: Security scan
security_scan:
  stage: security
  script:
  - echo "Running security scan..."
  - npm audit --json > $SECURITY_REPORT || true
  - cat $SECURITY_REPORT
  artifacts:
    paths:
    - $SECURITY_REPORT
    expire_in: 1 hour
  allow_failure: true

# Stage 4: GitLab Duo troubleshooting
duo_troubleshoot:
  stage: troubleshoot
  image:
    name: registry.gitlab.com/gitlab-org/duo-cli:latest
    entrypoint: [ "" ]
  script:
  - duo chat "Analyze the test failures in this pipeline and suggest potential fixes"
  when: on_failure
  artifacts:
    paths:
    - duo-chat-output.md
    expire_in: 1 hour
